service:
  name: nevezes

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  region: eu-central-1
  endpointType: REGIONAL

functions:
  getEvent:
    handler: src/events/handler.middyGetEvent
    events:
      - http:
          path: /api/events/{id}
          method: get         
          request:
            parameters:
              paths:
                id: false