name: Deploy master branch

on:
  push:
    branches:
      - master
        
jobs:
  deploy:    
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]    
    
    name: deploy

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ./backend
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: serverless deploy
      uses: aaronpanch/action-serverless@master
      with:
        args: deploy
      env:
        SERVICE_ROOT: ./backend
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
