name: Frontend Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: production build
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
      env:
        CI: true
    - name: create CNAME file
      run: echo "nevezes.reluxa.org" >./frontend/dist/CNAME
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: reluxa/reluxa.github.io
        target_branch: master
        build_dir: ./frontend/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_2 }}
